server:
  port: 8080

spring:
  application:
    name: Api-Gateway


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# පද්ධතියේ ආරක්ෂාව සඳහා (Optional)
management:
  endpoints:
    web:
      exposure:
        include: "*"